-- Mensajes archivados vinculados a conversation_history via history_id.

CREATE TABLE IF NOT EXISTS public.history_messages (
  id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  history_id             bigint NOT NULL
                         REFERENCES public.conversation_history(id)
                         ON DELETE CASCADE,
  source_message_id      bigint,
  source_conversation_id bigint,
  type                   text NOT NULL
                         CHECK (type IN ('in', 'out', 'note')),
  content                text NOT NULL DEFAULT '',
  sender_type            text NOT NULL
                         CHECK (sender_type IN ('client', 'agent', 'bot')),
  media_url              text,
  media_type             text
                         CHECK (
                           media_type IS NULL
                           OR media_type IN ('audio', 'image', 'video', 'document')
                         ),
  wa_message_id          text,
  status                 text
                         CHECK (
                           status IS NULL
                           OR status IN ('sent', 'delivered', 'read', 'failed')
                         ),
  created_at             timestamptz NOT NULL DEFAULT now(),
  archived_at            timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_history_messages_history_id
  ON public.history_messages (history_id);

CREATE INDEX IF NOT EXISTS idx_history_messages_history_created
  ON public.history_messages (history_id, created_at ASC);

ALTER TABLE public.history_messages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow anon read history_messages" ON public.history_messages;
CREATE POLICY "Allow anon read history_messages"
  ON public.history_messages
  FOR SELECT
  TO anon, authenticated
  USING (true);

GRANT SELECT ON public.history_messages TO anon, authenticated;
GRANT ALL ON public.history_messages TO service_role;
