CREATE TABLE IF NOT EXISTS public.quick_replies (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  shortcut text,
  content text NOT NULL,
  category text,
  is_active boolean NOT NULL DEFAULT true,
  created_by bigint REFERENCES public.agents(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz
);

CREATE UNIQUE INDEX IF NOT EXISTS quick_replies_shortcut_unique
ON public.quick_replies (lower(shortcut))
WHERE shortcut IS NOT NULL AND btrim(shortcut) <> '';

ALTER TABLE public.quick_replies ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow anon read quick_replies" ON public.quick_replies;
CREATE POLICY "Allow anon read quick_replies"
  ON public.quick_replies
  FOR SELECT
  TO anon, authenticated
  USING (true);

DROP POLICY IF EXISTS "Allow anon insert quick_replies" ON public.quick_replies;
CREATE POLICY "Allow anon insert quick_replies"
  ON public.quick_replies
  FOR INSERT
  TO anon, authenticated
  WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anon update quick_replies" ON public.quick_replies;
CREATE POLICY "Allow anon update quick_replies"
  ON public.quick_replies
  FOR UPDATE
  TO anon, authenticated
  USING (true)
  WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anon delete quick_replies" ON public.quick_replies;
CREATE POLICY "Allow anon delete quick_replies"
  ON public.quick_replies
  FOR DELETE
  TO anon, authenticated
  USING (true);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.quick_replies TO anon, authenticated;
GRANT ALL ON public.quick_replies TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.quick_replies_id_seq TO anon, authenticated, service_role;
